; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:mqtt_firmware]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<*> -<Calibration/> -<RemoteSensor/> -<CurrentSensor/>

lib_deps =
  madhephaestus/ESP32Servo
  adafruit/Adafruit NeoPixel
  knolleary/PubSubClient
  Preferences

[env:calibration]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<Calibration/> -<main.cpp>

lib_deps =
  madhephaestus/ESP32Servo
  adafruit/Adafruit NeoPixel
  Preferences
  ottowinter/ESPAsyncWebServer-esphome
  ottowinter/AsyncTCP-esphome

[env:remote_sensor]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<RemoteSensor/> -<main.cpp> -<Calibration/>

lib_deps =
  knolleary/PubSubClient
  adafruit/Adafruit NeoPixel
  esphome/ESPAsyncWebServer-esphome @ ^3.2.2
  esphome/AsyncTCP-esphome @ ^2.1.3

[env:currentsensor]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<CurrentSensor/> -<main.cpp> -<Calibration/> -<RemoteSensor/>

lib_deps =
  knolleary/PubSubClient
  Preferences
  esphome/ESPAsyncWebServer-esphome @ ^3.2.2
  esphome/AsyncTCP-esphome @ ^2.1.3

[env:mqtt_firmware_ota]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DOTA_ENABLED
build_src_filter = +<*> -<Calibration/> -<RemoteSensor/> -<CurrentSensor/>
; OTA upload (uncomment after first USB flash)
; upload_protocol = espota
; upload_port = baandsliber.local
; upload_flags =
;     --auth=fablabvejle!
;     --port=3232

lib_deps =
  madhephaestus/ESP32Servo
  adafruit/Adafruit NeoPixel
  knolleary/PubSubClient
  Preferences

[env:currentsensor_ota]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<CurrentSensor/> -<main.cpp> -<Calibration/> -<RemoteSensor/>
upload_protocol = espota
upload_port = currentsensor.local
upload_flags =
    --auth=fablabvejle!
  --port=3232

lib_deps =
  knolleary/PubSubClient
  Preferences
  esphome/ESPAsyncWebServer-esphome @ ^3.2.2
  esphome/AsyncTCP-esphome @ ^2.1.3